"use strict";
// Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
Object.defineProperty(exports, "__esModule", { value: true });
var x = 5;
var y = 10;
console.log("Is x == 5? I predict True.");
console.log(x == 5);
console.log("Is y == 10? I predict True.");
console.log(y == 10);
console.log("Is x != y? I predict True.");
console.log(x != y);
console.log("Is x < y? I predict True.");
console.log(x < y);
console.log("Is x!< y? I predict True.");
console.log(x < y);
console.log("Is x = y? I predict False.");
console.log(x == y);
console.log("Is x > y? I predict False.");
console.log(x > y);
console.log("Is y < x? I predict False.");
console.log(y < x);
console.log("Is x === y? I predict False.");
console.log(x === y);
console.log("Is x >= y? I predict False.");
console.log(x >= y);
